### Create a new user
POST http://localhost:3333/auth/signup
content-type: application/json

{
  "email": "test@test.pl",
  "password": "Zaq12wsx"
}

### Signin
POST http://localhost:3333/auth/signin
content-type: application/json

{
  "email": "test@test.pl", 
  "password": "Zaq12wsx"
}



