### Create user schedule
POST http://localhost:3333/schedule
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwiaWF0IjoxNjQ5ODI2MzA2LCJleHAiOjE2NDk5MTI3MDZ9.83oY8tDvXntD93V5h3ITWmaZ_KZod_aswEelP26KYEI

{
"schedules": [
  {"from": "2022-04-11T10:00:00+0000", "to": "2022-04-11T16:00:00+0000"}
]
}

### GET user schedules
GET  http://localhost:3333/schedule
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwiaWF0IjoxNjQ5ODI2MzA2LCJleHAiOjE2NDk5MTI3MDZ9.83oY8tDvXntD93V5h3ITWmaZ_KZod_aswEelP26KYEI