### Create a new user
POST http://localhost:3333/schedule
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDNAdGVzdC5jb20iLCJpYXQiOjE2NDk1ODU0NDksImV4cCI6MTY0OTY3MTg0OX0.-EoJTWohMMck7XpcxDtrU9tS1L3bdy0ZSi52KatReg0

{
"schedules": [
  {"from": "2022-04-10T10:00:00+0000", "to": "2022-04-10T12:00:00+0000"},
  {"from": "2022-04-10T14:00:00+0000", "to": "2022-04-10T17:00:00+0000"}
]
}

### Create a new user
GET  http://localhost:3333/schedule
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDNAdGVzdC5jb20iLCJpYXQiOjE2NDk1ODU0NDksImV4cCI6MTY0OTY3MTg0OX0.-EoJTWohMMck7XpcxDtrU9tS1L3bdy0ZSi52KatReg0

