### Create a reservation
POST http://localhost:3333/reservation
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwiaWF0IjoxNjQ5ODI2NDIzLCJleHAiOjE2NDk5MTI4MjN9.LKQhBAyevNVZMCdjxnAnQ6BONeQ3yJWB3Adh4AHXXlc

{
  "title": "Fryzjer",
  "date": "2022-04-11T12:00:00+0000"

}

### GET user reservations
GET  http://localhost:3333/reservation
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwiaWF0IjoxNjQ5ODI2NDIzLCJleHAiOjE2NDk5MTI4MjN9.LKQhBAyevNVZMCdjxnAnQ6BONeQ3yJWB3Adh4AHXXlc



### Delete reservation by id
DELETE  http://localhost:3333/reservation/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdEB0ZXN0LnBsIiwiaWF0IjoxNjQ5ODI2NDIzLCJleHAiOjE2NDk5MTI4MjN9.LKQhBAyevNVZMCdjxnAnQ6BONeQ3yJWB3Adh4AHXXlc

